In [50]:
import pandas as pd
import psycopg2
import os
import json

In [51]:
#read config file in input
with open("/home/imade/notebook/input_config.txt") as f:
    input_file=f.readline()
print("will process:",input_file)

will process: /home/imade/notebook/input/Liste des 2èmes années DS.xlsx

In [52]:
with open("/home/imade/notebook/config.json") as f:
    config = json.load(f)
print("Config:",config)
mydb = psycopg2.connect(database=config["database"], user=config["user"], password=config["password"], host=config["host"], port=config["port"], options=f'-c search_path=biabsence')

Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}

In [53]:
mycursor = mydb.cursor()
table="students"
mycursor.execute(f"SELECT * FROM information_schema.columns WHERE table_schema = 'students_db' AND table_name   = '{table}' ;")
myresult = mycursor.fetchall()
for value in myresult:
     print(value[3],":",value[7])

id : integer
first_name : character varying
last_name : character varying
email : character varying

In [57]:
def add_student(prenom,nom,email):
    with open("/home/imade/notebook/config.json") as f:
        config = json.load(f)
    print("Config:",config)
    mydb = psycopg2.connect(database=config["database"], user=config["user"], password=config["password"], host=config["host"], port=config["port"], options=f'-c search_path=biabsence')
    mycursor = mydb.cursor()
    mycursor.execute(f"SELECT * FROM students_db.students where email ='{email}'")
    myresult = mycursor.fetchall()
    if len(myresult) != 0:
        return myresult[0][0]
    if len(myresult) == 0:
        sql = "INSERT INTO students_db.students (first_name,last_name,email) VALUES (%s,%s,%s)"
        val = (prenom,nom,email)
        mycursor.execute(sql, val)
        mydb.commit()
        # print(mycursor.rowcount, "record inserted.")
        mycursor.execute(f"SELECT * FROM students_db.students where email ='{email}'")
        myresult = mycursor.fetchall()
        return myresult[0][0]

In [58]:
list_students = pd.read_excel(f"{input_file}",engine="openpyxl")
nom=[]
prenom=[]
email=[]
for index, row in list_students.iterrows():
    Nom_=row['Nom']
    prenom_ = Nom_.split(" ")[0]
    nom_ = Nom_.replace(prenom_+" ","")
    email_=f"{prenom_[0]}.{nom_.split(' ')[0]}@insea.ac.ma"
    
    nom.append(nom_)
    prenom.append(prenom_)
    email.append(email_)
    
list_students["prenom"]=prenom
list_students["nom"] = nom
list_students["email"]=email
del list_students['Nom']
list_students

        prenom                   nom                     email
0   Abdelakbir                MENANI      A.MENANI@insea.ac.ma
1       Abdoul  Madjid SANOUSSI LABO      A.Madjid@insea.ac.ma
2        Amina              EZZOUINE    A.EZZOUINE@insea.ac.ma
3        Amine               AJARRAY     A.AJARRAY@insea.ac.ma
4        Amine               CHEDDAD     A.CHEDDAD@insea.ac.ma
5        Amine              ELOMAIRI    A.ELOMAIRI@insea.ac.ma
6        Andre                SINARE      A.SINARE@insea.ac.ma
7         Asma                OUSSAR      A.OUSSAR@insea.ac.ma
8       Aymane                 HAMDI       A.HAMDI@insea.ac.ma
9        Ayoub              ELHADINE    A.ELHADINE@insea.ac.ma
10     Chaimaa             BELKARKOR   C.BELKARKOR@insea.ac.ma
11     Chaimae      BENALLAL HASSANI    C.BENALLAL@insea.ac.ma
12       Hajar                CHAFAI      H.CHAFAI@insea.ac.ma
13       Hajar               HOUMANE     H.HOUMANE@insea.ac.ma
14       Hamza                   DAH         H.DAH@insea.ac.ma
15       Hamza              LAGRAMEZ    H.LAGRAMEZ@insea.ac.ma
16     Ibtihal                MOURAD      I.MOURAD@insea.ac.ma
17     Idrissa               KONKOBO     I.KONKOBO@insea.ac.ma
18       Imane            BELMEZOUAR  I.BELMEZOUAR@insea.ac.ma
19      Kawtar              BENSETTI    K.BENSETTI@insea.ac.ma
20     Youssef        Amine KHALLOUQ       Y.Amine@insea.ac.ma
21     Mohamed               AMALLAH     M.AMALLAH@insea.ac.ma
22     Mohamed               AGOURAM     M.AGOURAM@insea.ac.ma
23      Moussa                SIDIBÉ      M.SIDIBÉ@insea.ac.ma
24     Nohaila              CHAHBOUN    N.CHAHBOUN@insea.ac.ma
25        Rida                OUHMIZ      R.OUHMIZ@insea.ac.ma
26  Saifeddine             ELHAIRECH   S.ELHAIRECH@insea.ac.ma
27    Soukaina               DAOUAJI     S.DAOUAJI@insea.ac.ma
28       Tarik               MAJJATI     T.MAJJATI@insea.ac.ma
29     Yasmine              ELHILALI    Y.ELHILALI@insea.ac.ma
30     Yassine             AMAGHOUSS   Y.AMAGHOUSS@insea.ac.ma
31     Yassine                 SADKI       Y.SADKI@insea.ac.ma

In [59]:
for index, row in list_students.iterrows():
    nom=row['nom']
    prenom=row['prenom']
    email=row['email']
    id_student=add_student(prenom,nom,email)
    print(id_student)

Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
1
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
2
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
3
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
4
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
5
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
6
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
7
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
8
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
9
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
10
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
11
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
12
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
13
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
14
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
15
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
16
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
17
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
18
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
19
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
20
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
21
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
22
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
23
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
24
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
25
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
26
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
27
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
28
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
29
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
30
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
31
Config: {'database': 'students', 'user': 'postgres', 'password': 'Speaklui1234', 'host': 'localhost', 'port': '5432'}
32

In [60]:
list_students.to_excel(f"/home/imade/notebook/output/{input_file.split('/')[-1]}",engine="openpyxl",index=False)

In [61]:
os.system(f'mv "{input_file}" "/home/imade/notebook/processed/"')

0